baseURL: https://dataengconf.com.au/
languageCode: en-us
title: DataEngConfAU - Sydney
theme: leo-fresh
googleAnalytics: UA-156065222-1
#Disables warningss
disableKinds:
 -taxonomy
 -taxonomyTerm


params:
 # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: DataEngConfAU - 4th of August 2020
  navbarlogo:
  # Logo (from static/images/logos/___)
  #  image: logos/fresh.svg
  #  link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: DataEngConfAU Sydney
    # Hero subtitle (optional)"
    subtitle: "Conference: Tuesday, 4th of August 2020."
    subtitle2: "Workshops: Monday, 3rd of August 2020."
    # Button text
    buttontext: Learn more
    # Where the main hero button links to
    buttonlink: "/#about"
    # Hero image (from static/images/___)
    # image: illustrations/worker.svg
    image: undraw/design_data.svg
  navbar:
  - title: About
    url: /#about
  - title: Sponsors
    url: /#sponsors
  - title: Key Dates
    url: /#keydates
  # - title: Speakers
  #   url: /#speakers
  # - title: Location
  #   url: /#location
  - title: Code of Conduct
    url: /#codeconduct
  - title: Organisers
    url: /#organisers
  - title: Contact
    url: /#contact

  
  about:
    title: What's DataEngConfAU All About?
    additional_image: computer_sitting_transparent.png
    text: "Data Engineering is a buzzword that has vegemite appeal. For some, it points to the future of how businesses do data in a post-cloud world, and for others, they struggle to understand where it fits in a world full of data science / ML and AI buzzwords. \n DataEngConfAU is a single track, one-day event that moves away from the hype and focuses on the reality data engineering based solutions. It’s about fostering a community locally and helping all of us learn from each other as we embrace a new way of building applications. \n DataEngConfAU is the evolution of the hugely popular Sydney Data Engineering meetup, and we are building on the success of it since its 2017 commencement. We are holding the day in a to be determined venue at Sydney’s CBD on 4th August 2019. \n As a community event, we aim to keep conference fees to a minimum - we don’t want to put a huge financial barrier between attendees and a great event. Sponsorship also allows us to offer a small number of free invitations to disadvantaged or underrepresented community members. "
    images: 
    - imageheader: Connect
      image: undraw/connecting_teams.svg
    - imageheader: Collaborate
      image: undraw/pair_programming.svg
    - imageheader: Learn
      image: undraw/new_ideas.svg

  sponsors:
    title: Sponsors
    subtitle: We need your help to make great things happen!
    # subtitle: Thank you!

  keydates:
    title: Key Dates
    dates:
    - title: Febuary 1
      suffix: st
      text: Call For Papers Opens
    - title: June 1
      suffix: st
      text: Call For Papers Closes
    - title: August 3
      suffix: rd
      text: Workshops
    - title: August 4
      suffix: th
      text: Main Conference

  # speakers:
  #   title: Speakers
  #   subtitle: Coming Soon!
    # speaker_list:
    # - name: Rick Astley
    #   picture: download.jpeg
    #   text: We're no strangers to love
    # - name: Rick Astley
    #   picture: download.jpeg
    #   text: You know the rules and so do I
    # - name: Rick Astley
    #   picture: download.jpeg
    #   text: A full commitment's what I'm thinking of
    # - name: Rick Astley
    #   picture: download.jpeg
    #   text: You wouldn't get this from any other guy

   
  # location:
  #   title: Location
  #   subtitle: To be confirmed!
  #   MAPS_API_KEY: xxx
  
  codeconduct:
    title: Code Of Conduct
    # subtitle: Thank you!
    image: undraw/thinker.svg
    text: Our conference is dedicated to providing a welcoming experience for everyone, regardless of how one identifies. We do not tolerate harassment or discrimination of anyone in any form. Inappropriate language and imagery is not permitted for any conference venue, including talks, workshops, parties, twitter and other online media. 
    # Our conference is dedicated to providing a harassment-free conference experience for everyone, regardless of gender, identity, expression, age, sexual orientation, disability, ethnicity, religion (or lack thereof), or technology choices. We do not tolerate harassment of conference participants in any form. Sexual language and imagery is not appropriate for any conference venue, including talks, workshops, parties, Twitter and other online media. Conference participants violating these rules may be sanctioned or expelled from the conference without a refund at the discretion of the conference organisers.



  # TODO: Potentially make tiles smaller
  organisers:
    title: Organisers
    subtitle: Our awesome organisers and volunteers
    first_column:
    - title: Peter Hanssens
      picture: peter_hanssens.jpeg
      text: Solutions Architect
    - title: Leo Hoare
      picture: leo_hoare.jpeg
      text: Associate Data Engineer
    # - title: Yash Sharma
    #   picture: yash_sharma.jpeg
    #   text: Senior Data Engineer
    second_column:
    - title: Karen Davis
      picture: karen_davis.JPG
      text: Senior Data Engineer
    - title: Katie Peterson
      picture: katie_peterson.jpeg
      text: Software Developer
    third_column:
    - title: Simon Aubury
      picture: simon_aubury.jpeg
      text: Principal Data Engineer
    - title: David Tout
      picture: david_tout.jpeg
      text: Principal Data & Cloud Architect

  mailinglist:
    title: Register Your Interest

  contact:
    title: Contact
    email: sydney@dataengconf.com.au
    socialmedia:
    - social: twitter
      link: https://twitter.com/dataengconfau
    - social: email
      link: mailto:sydney@dataengconf.com.au?Subject=DataEngConf
    - social: linkedin
      link: https://www.linkedin.com/company/dataengconfau/about/
