baseURL: https://dataengconf.com.au/
languageCode: en-us
title: DataEngConf - Sydney
theme: leo-fresh
googleAnalytics: UA-156065222-1
#Disables warningss
disableKinds:
 -taxonomy
 -taxonomyTerm


params:
 # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: 
  navbarlogo:
  # Logo (from static/images/logos/___)
  #  image: logos/fresh.svg
  #  link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: DataEngConf Sydney
    # Hero subtitle (optional)
    subtitle: Tuesday, 4th of August 2020 (Main conference). Workshops on the 3rd!
    # Button text
    buttontext: Learn more
    # Where the main hero button links to
    buttonlink: "/#about"
    # Hero image (from static/images/___)
    # image: illustrations/worker.svg
    image: undraw/design_data.svg
  navbar:
  - title: About
    url: /#about
  - title: Sponsors
    url: /#sponsors
  - title: Speakers
    url: /#speakers
  # - title: Location
  #   url: /#location
  - title: Code of Conduct
    url: /#codeconduct
  - title: Organisers
    url: /#organisers
  - title: Contact
    url: /#contact

  
  about:
    title: What's DataEngConfAU All About?
    additional_image: computer_sitting_transparent.png
    text: DataEngConfAU
    images: 
    - imageheader: Connect
      image: undraw/connecting_teams.svg
    - imageheader: Collaborate
      image: undraw/pair_programming.svg
    - imageheader: Learn
      image: undraw/new_ideas.svg

  sponsors:
    title: Sponsors
    subtitle: We need your help to make great things happen!
    # subtitle: Thank you!

  speakers:
    title: Speakers
    subtitle: Coming Soon!
    # speaker_list:
    # - name: Rick Astley
    #   picture: download.jpeg
    #   text: We're no strangers to love
    # - name: Rick Astley
    #   picture: download.jpeg
    #   text: You know the rules and so do I
    # - name: Rick Astley
    #   picture: download.jpeg
    #   text: A full commitment's what I'm thinking of
    # - name: Rick Astley
    #   picture: download.jpeg
    #   text: You wouldn't get this from any other guy

   
  # location:
  #   title: Location
  #   subtitle: To be confirmed!
  #   MAPS_API_KEY: xxx
  
  codeconduct:
    title: Code Of Conduct
    # subtitle: Thank you!
    image: undraw/thinker.svg
    text: Our conference is dedicated to providing a harassment-free conference experience for everyone, regardless of gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion (or lack thereof), or technology choices. We do not tolerate harassment of conference participants in any form. Sexual language and imagery is not appropriate for any conference venue, including talks, workshops, parties, Twitter and other online media. Conference participants violating these rules may be sanctioned or expelled from the conference without a refund at the discretion of the conference organisers.


  # TODO: Potentially make tiles smaller
  organisers:
    title: Organisers
    subtitle: Our awesome organisers and volunteers
    first_column:
    - title: Peter Hanssens
      picture: peter_hanssens.jpeg
      text: Solution Architect
    - title: Leo Hoare
      picture: leo_hoare.jpeg
      text: Associate Data Engineer
    second_column:
    - title: Karen Davis
      picture: karen_davis.jpeg
      text: Senior Data Engineer
    - title: Yash Sharma
      picture: yash_sharma.jpeg
      text: Senior Data Platform Engineer
    - title: Wade Jensen
      picture: wade_jensen.jpeg
      text: Software Engineer - Data & Infastructure
    third_column:
    - title: Simon Aubury
      picture: simon_aubury.jpeg
      text: Principal Data Engineer
    - title: David Tout
      picture: david_tout.jpeg
      text: Principal Data & Cloud Architect

  contact:
    title: Contact
    email: sydney@dataengconf.com.au



  # footer:
  #   # Logo (from /images/logos/___)
  #   logo: fresh-white-alt.svg
  #   # Social Media Title
  #   socialmediatitle: Follow Us
  #   # Social media links (GitHub, Twitter, etc.). All are optional.
  #   socialmedia:
  #     - link: https://twitter.com/lucperkins
  #       icon: twitter
  #     - link: https://linkedin.com/dataengconfau
  #       # Icons are from Font Awesome
  #       icon: linkedin
  #   # bulmalogo: true
  #   quicklinks:
  #     column1:
  #       title: "Sponsors"
  #       links:
  #       - text: Sponsorship Prospectus
  #         link: /
  #       # - text: Why choose our product?
  #       #   link: /
  #     column2:
  #       title: "Venue"
  #       links:
  #       - text: Coming Soon!
  #         link: /
  #       # - text: User guides
  #       #   link: /
  #     # column3:
  #     #   title: "Blog"
  #     #   links:
  #     #   - text: Latest news
  #     #     link: /blog/first

