[[plugins]]
package = 'netlify-plugin-env'
  [plugins.inputs]
  mode = 'prefix'

[build]
  command   = "npm run build"
  functions = "out_functions"
  publish   = "out_publish"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production]
  environment = { NODE_VERSION = "14" }

[context.deploy-preview]
  environment = { NODE_VERSION = "14" }

[context.branch-deploy]
  environment = { NODE_VERSION = "14" }